### ISSUE TITLE
Google?

### ISSUE THREAD

**Issue by Hidan123** [shiftcodeYT/PokeBot2#13]
Working very well, nice work. The only problem is I get spammed with "Argument Null Refference - Restarting" after a while(30min-40min) most likely due to the fact I'm using Google, any work-around/fix?

**Comment by shiftcodeYT** [comment]
I honestly have no idea why. I'm using this personally on many accounts, and this error only occurs on one of them.

**Comment by Hidan123** [comment]
:C i wanted to set it up for night but with that bug oh well anyway good work with the bot waiting for solution !

**Comment by Xlepto** [comment]
I'm having the same problem as well.

**Comment by ZivC12** [comment]
Same problem as well

**Comment by kmlalpr** [comment]
You have to delete tokens.txt and restart the program. But it is bug.

**Comment by Xlepto** [comment]
^^ That fixed the problem!

**Comment by Hidan123** [comment]
Yea it fixed it but u need to do it manually that suck...

**Comment by Albeoris** [comment]
**Because:**
tokenResponse.expires_in	3600	int

You need to refresh an access token.

**Comment by shiftcodeYT** [comment]
Fixed in #20, will release today evening.

**Comment by ilikesomething** [comment]
does it have been already released yet ? (since i don't know in what timezone you are)
Asking cause i still have the same issue

**Comment by Alienater** [comment]
I have the same issue, so a release time would be nice, I cant seem to run it more than an hour and id like to go all night.

Best

**Comment by malverde** [comment]
When is release

**Comment by tunayuyar** [comment]
[re.zip](https://github.com/shiftcodeYT/PokeBot2/files/380233/re.zip)


I compiled this from latest git, i think it is working correctly, also shows the names of pokestops

**Comment by tunayuyar** [comment]
Also please note that coordinates are not from default/git, it is my custom coordinates so dont forget to change it, if you were using with another.

**Comment by kmlalpr** [comment]
Hocam türk müsünüz?

**Comment by tunayuyar** [comment]
@kmlalpr  evet ? sohbete şurda devam edelim : https://discord.gg/gY3v9

**Comment by Alienater** [comment]
@tunayuyar, would you be able to link a video that shows how to do that in visual studios?

**Comment by tunayuyar** [comment]
@Alienater just google how to compile/build in visual studio 2015

**Comment by Alienater** [comment]
I have im just getting a lot of errors, my exe seems to never be created when I press ctrl+f5
